import { createContext } from "react";

export const DiscoverContext = createContext({
  sortBy: "",
  setSortBy: () => {},
  countries: [],
  setCountries: () => {},
  countryValue: null,
  setCountryValue: () => {},
  release_date_gte: null,
  release_date_lte: null,
  setRelease_date_gte: () => {},
  setRelease_date_lte: () => {},
  genresMovieList: [],
  setgenresMovieList: () => {},
  genreSelected: {},
  setGenreSelected: () => {},
  certificationMovieList: [],
  certificationSelected: {},
  setCertificationSelected: () => {},
  languagesMovieList: [],
  setLanguagesMovieList: () => {},
  languageValue: null,
  setLanguageValue: () => {},
  userScoreValue: 0,
  setUserScoreValue: () => {},
  userVotesValue: 0,
  setUserVotesValue: () => {},
  runtimeValue: 0,
  setRuntimeValue: () => {},
  watchCountry: [],
  setWatchCountry: () => {},
  watchCountryValue: null,
  setWatchCountryValue: () => {},
  watchProviderMovies: [],
  setWatchProviderMovies: () => {},
  setWatchProviderMoviesSelected: () => {},
  watchProviderMoviesSelected: {},
});
